name: Go Test Workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21  # Update to match your Go version

      - name: Install Dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run Go Tests (Verbose)
        run: go test -v ./...

